# とりあえずファイルだけ作ったがGoのcodegenはほぼ見送る予定 TSはopenapi-fetchを使う
openapi: "3.1.3"
info:
  title: SURUME-Local
  description: surume local
  version: "1.2.0"
servers:
  - url: http://{host}:{port}/api
    description: "dev env (port number is defined code level)"
    variables:
      host:
        default: localhost
      port:
        default: "24601"
tags:
  - name: History
    description: |
      history log data <br>
  - name: System
    description: |
      - Entra ID info (no Graph API) <br>
  - name: Teams
    description: Teams info from MS Graph API
  - name: Chat
    description: |
      Teams Chat <br>
paths:
  /system/reset:
    delete:
      summary: Initialize system data
      description: |
        Initialize system data <br>
        各データの削除の挙動<br>
        - DBのテーブルを初期化
          - 存在しない場合はエラーを返さず、再作成する
      tags: [System]
      operationId: Init
      deprecated: false
      requestBody:
        $ref: "#/components/requestBodies/DeleteInitRequestBody"
      responses:
        2XX:
          $ref: "#/components/responses/DeleteTargetResponse"
        default:
          $ref: "#/components/responses/500InternalServerError"
  /system/entraid:
    post:
      summary: setup
      description: |
        setup app data <br>
      tags: [System]
      operationId: SetEntraIdInfo
      deprecated: false
      requestBody:
        $ref: "#/components/requestBodies/PostInitRequestBody"
      responses:
        2XX:
          $ref: "#/components/responses/SetEntraIdInfoResponse"
        5XX:
          $ref: "#/components/responses/500InternalServerError"
        default:
          $ref: "#/components/responses/500InternalServerError"
  /entraid:
    get:
      summary: EntraID info
      description: |
        get MS EntraID data info <br>
      tags: [System]
      operationId: GetEntraIdInfo
      deprecated: false
      responses:
        2XX:
          $ref: "#/components/responses/GetEntraIdInfoResponse"
        default:
          $ref: "#/components/responses/500InternalServerError"
  /system/version:
    get:
      summary: version
      description: |
        get app version<br>
      tags: [System]
      operationId: GetVersion
      deprecated: false
      responses:
        2XX:
          $ref: "#/components/responses/VersionResponse"
        default:
          $ref: "#/components/responses/500InternalServerError"

  /system/maintenance:
    put:
      summary: mentenance info
      description: |
        mentenance info <br>
      tags: [System]
      operationId: Init
      deprecated: false
      requestBody:
        $ref: "#/components/requestBodies/SwitchMaintenanceModeRequestBody"
      responses:
        2XX:
          $ref: "#/components/responses/MaintenanceResponse"
        default:
          $ref: "#/components/responses/500InternalServerError"
  /util/validateTemplate:
    post:
      summary: validation template xlsx file for chats
      description: |
        validation template xlsx file for chats <br>
      tags:
        - Teams
      operationId: Validate Template
      deprecated: false
      requestBody:
        $ref: "#/components/requestBodies/PostXlsxRequestBody"
      responses:
        2XX:
          $ref: "#/components/responses/ValidateXlsxFileReponse"
        default:
          $ref: "#/components/responses/500InternalServerError"
components:
  schemas:
    success_state:
      type: string
      enum:
        - UPDATE
        - CREATE
    result_success:
      type: boolean
      default: true
    system_mode:
      type: string
      enum:
        - mentenance
        - goon
    version_info:
      type: object
      properties:
        name:
          type: string
          description: name
          default: SURUME Local
          example: app
        version:
          type: integer
          description: version
          example: 2
    ErrorBase:
      type: object
      properties:
        success:
          type: boolean
          description: always must be false
          default: false
          example: false
        code:
          type: string
          description: error code
        message:
          type: string
          description: error message
      required:
        - success
        - message

    EntraIdInfo:
      type: object
      properties:
        authority:
          type: string
          # format指定 format: ????
          example: azure.sample.com
        clientid:
          type: string
          # format指定 format: ????
          example: xxxx-xxxx-xxxx-xxxx
      required:
        - authority
        - clientid
    InitTargetList:
      type: array
      items:
        type: string
        enum:
          - entraid_info
          - history
    Init:
      # 他にも追加するかもしれないので一応allofにしておく
      allOf:
        - properties:
            target:
              $ref: "#/components/schemas/InitTargetList"
      required:
        - target
    XlsxFile:
      type: object
      properties:
        filename:
          type: string
        file:
          type: string
          format: binary
      required:
        - file
    ChatMessage:
      type: object
      properties:
        to:
          type: string
        content:
          type: string
      required:
        - to
        - content
    ChatMember:
      type: object
      properties:
        chatid:
          type: string
        workbookname:
          type: string
      required:
        - chatid
        - workbookname
    ValidateBroadcast:
      type: object
      properties:
        success:
          type: boolean
          default: true
        data:
          type: array
          items:
            $ref: "#/components/schemas/ChatMessage"
      required:
        - success
        - data
    ValidateChatMember:
      type: object
      properties:
        success:
          type: boolean
          default: true
        data:
          type: array
          items:
            $ref: "#/components/schemas/ChatMember"
      required:
        - success
        - data



  requestBodies:
    DeleteInitRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Init"
    PostInitRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/EntraIdInfo"

    SwitchMaintenanceModeRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              mode:
                $ref: "#/components/schemas/system_mode"
            required:
              - mode
    PostXlsxRequestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              xlsx:
                $ref: "#/components/schemas/XlsxFile"
              target:
                type: string
              type:
                type: string
            required:
              - xlsx
              - target
              - type

  responses:
    DeleteTargetResponse:
      description: success operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
            required:
              - success
    VersionResponse:
      description: version
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              data:
                $ref: "#/components/schemas/version_info"
            required:
              - success
              - data

    SetEntraIdInfoResponse:
      description: setting entra id info
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              data:
                $ref: "#/components/schemas/success_state"
            required:
              - success
              - data
    GetEntraIdInfoResponse:
      description: todo
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              data:
                $ref: "#/components/schemas/EntraIdInfo"
            required:
              - success
              - data
    MaintenanceResponse:
      description: ret
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
              mode:
                $ref: "#/components/schemas/system_mode"
            required:
              - success
              - mode
    ValidateXlsxFileReponse:
      description: validate xlsx
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/ValidateBroadcast"
              - $ref: "#/components/schemas/ValidateChatMember"

    500InternalServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBase"
          example:
            success: false
            code: "999"
            message: "system error!"
